"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./context/AuthContext";
import { BrowserRouter } from 'react-router-dom'

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Pantry",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BrowserRouter>
          <AuthContextProvider>
            {children}
          </AuthContextProvider>
        </BrowserRouter>
      </body>
    </html>
  );
}
